### ISSUE TITLE
ciao pirletti 

### ISSUE THREAD

**Issue by nicolezattarin** [AleCapoPhys/HeartRateEstimation#1]
![f7900d21f5031beac20d94889fe7c06b5166](https://user-images.githubusercontent.com/72666452/148814414-a7435d2e-9524-4fcd-8752-970556e7575f.gif)

**Comment by AleCapoPhys** [comment]
Thanks for the essential debugging nicole! Fixed

**Comment by nicolezattarin** [comment]
I was so proud of my gattini, you broke my heart. reopen ittt
